name: ipp
description: A starting point for Dart IPP package, for Using IPP(internet printer protocol) to Easyly print files, PDF, or other documents, See more information, see demo or examples.
version: 1.0.8
homepage: https://gitee.com/darto/ipp

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  html: ^0.15.4
  http: ^1.1.0
  convert: ^3.1.1
 

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.6
